version: 0.2

env:
  parameter-store:
    SHARED_SERVICES_ECR_BASE_URL: "/codebuild/pttp-ci-ima-pipeline/shared_services_base_repository_url"
    DEVL_SUBSCRIPTION_ID: "/codebuild/pttp-ci-ima-pipeline/devl-subscription-id"
    DEVL_CLIENT_ID: "/codebuild/pttp-ci-ima-pipeline/devl-client-id"
    DEVL_CLIENT_SECRET: "/codebuild/pttp-ci-ima-pipeline/devl-client-secret"
    DEVL_TENANT_ID: "/codebuild/pttp-ci-ima-pipeline/devl-tenant-id"

phases:
  install:
    on-failure: CONTINUE
    commands:
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh

  build:
    commands:
      - export AWS_DEFAULT_REGION=eu-west-2
      - KUBERNETES_NAMESPACE=$ENV ./scripts/deploy_kubernetes.sh


  post_build:
    commands:
      - echo "POST BUILD"
