version: 0.2

env:
  variables:
    TF_INPUT: 0
    TF_VAR_env: $ENV
    TF_IN_AUTOMATION: true
    TF_VAR_owner_email: pttp@justice.gov.uk
  parameter-store:
    OUTPUTS: "/terraform_staff_infrastructure_monitoring/$ENV/outputs"
    
phases:
  install:
    on-failure: CONTINUE
    commands:
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh

  build:
    commands:
      - export AWS_DEFAULT_REGION=eu-west-2
      - ./scripts/deploy_kubernetes.sh


  post_build:
    commands:
      - echo "POST BUILD"
