version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: "/moj-network-access-control/docker/username"
    DOCKER_PASSWORD: "/moj-network-access-control/docker/password"
    DEVL_subscriptionId: "/codebuild/pttp-ci-ima-pipeline/devl-subscription-id"
    DEVL_clientId: "/codebuild/pttp-ci-ima-pipeline/devl-client-id"
    DEVL_clientSecret: "/codebuild/pttp-ci-ima-pipeline/devl-client-secret"
    DEVL_tenantId: "/codebuild/pttp-ci-ima-pipeline/devl-tenant-id"
    PREPROD_subscriptionId: "/codebuild/pttp-ci-ima-pipeline/preprod-subscription-id"
    PREPROD_clientId: "/codebuild/pttp-ci-ima-pipeline/preprod-client-id"
    PREPROD_clientSecret: "/codebuild/pttp-ci-ima-pipeline/preprod-client-secret"
    PREPROD_tenantId: "/codebuild/pttp-ci-ima-pipeline/preprod-tenant-id"

phases:
  install:
    on-failure: CONTINUE
    commands:
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh

  build:
    commands:
      - export AWS_DEFAULT_REGION=eu-west-2
      - ./scripts/deploy_kubernetes.sh development

  post_build:
    commands:
      - echo "POST BUILD"
