version: 0.2

env:
  variables:
    AWS_REGION: eu-west-2
  parameter-store:
    ROLE_ARN: /codebuild/pttp-ci-infrastructure-core-pipeline/development/assume_role # tests hardcoded to only run in development

phases:
  install:
    commands:
      - echo test install

  build:
    commands:
      - echo test


# NB: This buildspec is just a stub until we have some tests to run as part of CI