apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-alertmanager
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: {{ .Values.alertmanager.image }}:latest
        command: ["alertmanager"]
        args: 
          - "--config.file=/config/alertmanager.yml"
{{ if .Values.debug  }}
          - "--log.level=debug"
{{ end }}
        ports:
        - containerPort: 9093
          protocol: TCP
        volumeMounts:
        - name: configuration
          mountPath: "/config"
        - name: templates
          mountPath: "/templates"
      - name: alertmanager-configmap-reload
        image: {{ .Values.configmap_reload.image }}:latest
        args:
          - "--volume-dir=/config"
          - "--webhook-url=http://127.0.0.1:9093/-/reload"
        volumeMounts:
        - name: configuration
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: configuration
        configMap:
          name: alertmanager-configmap
          items:
          - key: "alertmanager.yml"
            path: "alertmanager.yml"
      - name: templates
        configMap:
          name: alertmanager-slack-alerts-templates-configmap
          items:
          - key: "slack-alerts-templates.tmpl"
            path: "slack-alerts-templates.tmpl"