apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-alertmanager
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 10.180.100.0/22
spec:
  type: LoadBalancer
  selector:
    app: alertmanager
  ports:
    - name: http
      protocol: TCP
      port: 9093
      targetPort: 9093