apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-azure-devl-metrics-exporter-configmap
data:
  azure.yml: |
    active_directory_authority_url: "https://login.microsoftonline.com/"
    resource_manager_url: "https://management.azure.com/"
    credentials:
      subscription_id: "{{ .Values.azure.devl.subscription_id }}"
      client_id: "{{ .Values.azure.devl.client_id }}"
      client_secret: "{{ .Values.azure.devl.client_secret }}"
      tenant_id: "{{ .Values.azure.devl.tenant_id }}"

    resource_tags:
      - resource_tag_name: "virtualMachinesMonitor"
        resource_tag_value: "prometheus"
        resource_types:
          - "Microsoft.Automation/automationAccounts"
        metrics:
          - name: "TotalJob"
        resource_types:
          - "Microsoft.Compute/virtualMachines"
        metrics:
          - name: "Percentage CPU"
          - name: "Inbound Flows"
          - name: "Outbound Flows"
          - name: "Network In Total"
          - name: "Network Out Total"
          - name: "OS Disk Queue Depth"
        resource_types:
          - "Microsoft.EventHub/namespaces"
        metrics:
          - name: "QuotaExceededErrors"
          - name: "UserErrors"
          - name: "ServerErrors"
          - name: "SuccessfulRequests"
        resource_types:
          - "Microsoft.Network/loadbalancers"
        metrics:
          - name: "ByteCount"
          - name: "DipAvailability"
          - name: "VipAvailability"
        resource_types:
          - "Microsoft.Network/virtualnetworkgateways"
        metrics:
          - name: "AverageBandwidth"
          - name: "TunnelIngressBytes"
          - name: "TunnelEgressBytes"
          - name: "TunnelAverageBandwidth"
        resource_types:
          - "Microsoft.Network/loadBalancers"
        metrics:
          - name: "ByteCount"
          - name: "PacketCount"
          - name: "DipAvailability"
