apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-azure-devl-metrics-exporter-configmap
data:
  azure.yml: |
    active_directory_authority_url: "https://login.microsoftonline.com/"
    resource_manager_url: "https://management.azure.com/"
    credentials:
      subscription_id: "{{ .Values.azure.devl.subscription_id }}"
      client_id: "{{ .Values.azure.devl.client_id }}"
      client_secret: "{{ .Values.azure.devl.client_secret }}"
      tenant_id: "{{ .Values.azure.devl.tenant_id }}"

    resource_tags:
      - resource_tag_name: "virtualMachinesMonitor"
        resource_tag_value: "prometheus"
        resource_types:
          - "Microsoft.Compute/virtualMachines"
        metrics:
          - name: "CPU Credits Consumed"
          - name: "Percentage CPU"
          - name: "Data Disk Read Bytes/Sec"
          - name: "Disk Write Bytes"
      - resource_tag_name: "loadBalancersMonitor"
        resource_tag_value: "prometheus"
        resource_types:
          - "Microsoft.Network/loadBalancers"
        metrics:
          - name: "ByteCount"
          - name: "PacketCount"
          - name: "DipAvailability"
