apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-azure-devl-metrics-exporter-configmap
data:
  azure.yml: |
    active_directory_authority_url: "https://login.microsoftonline.com/"
    resource_manager_url: "https://management.azure.com/"
    credentials:
      subscriptionId: "{{ .Values.azure.devl.subscriptionId }}"
      clientId: "{{ .Values.azure.devl.clientId }}"
      clientSecret: "{{ .Values.azure.devl.clientSecret }}"
      tenantId: "{{ .Values.azure.devl.tenantId }}"

    resource_tags:
      - resource_tag_name: "prometheusautomationAccounts"
        resource_tag_value: "tomonitor"
        resource_types:
          - "Microsoft.Automation/automationAccounts"
        metrics:
          - name: "TotalJob"

      - resource_tag_name: "prometheusloadbalancers"
        resource_tag_value: "tomonitor"
        resource_types:
          - "Microsoft.Network/loadBalancers"
        metrics:
          - name: "ByteCount"
          - name: "DipAvailability"
          - name: "VipAvailability"
          - name: "SnatConnectionCount"
          - name: "SYNCount"

      - resource_tag_name: "prometheusvirtualMachines"
        resource_tag_value: "tomonitor"
        resource_types:
          - "Microsoft.Compute/virtualMachines"
        metrics:
          - name: "Available Memory Bytes"
          - name: "Inbound Flows"
          - name: "Outbound Flows"
          - name: "Network In Total"
          - name: "Network Out Total"
          - name: "OS Disk Queue Depth"
          - name: "OS Disk Read Bytes/Sec"
          - name: "OS Disk Write Bytes/Sec"
          - name: "Percentage CPU"

      - resource_tag_name: "prometheusvirtualnetworkgateways"
        resource_tag_value: "tomonitor"
        resource_types:
          - "Microsoft.Network/virtualNetworkGateways"
        metrics:
          - name: "AverageBandwidth"
          - name: "TunnelAverageBandwidth"
          - name: "TunnelEgressBytes"
          - name: "TunnelIngressBytes"

