apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: {{ .Values.certificateAlertsSlackChannel }}
    privateKeySecretRef:
      name: letsencrypt
    server: {{ .Values.letsencryptDirectoryUrl }}
    solvers: 
      - dns01:
          route53:
            region: eu-west-2
            hostedZoneID: {{ .Values.publicHostedZoneId }}