apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: {{ .Values.cert_slack_email }}
    privateKeySecretRef:
      name: letsencrypt
    server: {{ .Values.letsencrypt_url }}
    solvers: 
      - dns01:
          route53:
            region: eu-west-2
            hostedZoneID: {{ .Values.public_hosted_zone_id }}