apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: prometheus-{{ .Release.Namespace }}.{{ .Values.hostedZonePrivate }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-thanos-querier
              port:
                number: 10902
  - host: alertmanager-{{ .Release.Namespace }}.{{ .Values.hostedZonePrivate }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-alertmanager
              port:
                number: 9093
