apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: {{ .Release.Name }}-kube-state-metrics
    app.kubernetes.io/version: 2.5.0
  name: {{ .Release.Name }}-kube-state-metrics
  namespace: {{ .Values.environment }}
spec:
  ports:
  - name: http-metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: telemetry
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app.kubernetes.io/name: kube-state-metrics