apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: {{ .Values.prometheus.image }}:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: alert-rules
          mountPath: "/alerts"
          readOnly: true
      volumes:
      - name: alert-rules
        configMap:
          name: prometheus-alert-rules-configmap
          items:
          - key: "alertRules.yml"
            path: "alertRules.yml"