apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-thanos-querier
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 10.180.100.0/22
spec:
  type: LoadBalancer
  selector:
    app: thanos-querier
  ports:
    - name: http
      protocol: TCP
      port: 10902
      targetPort: 10902